language: cpp
os:
  - linux
  - osx
  - windows
dist: trusty
osx_image: xcode9.4
env: 
  - STEAMLESS=YES
  - ""
before_install:
  - source .travis_before_install.sh
script:
  - bash .travis_run.sh
deploy:
  - skip_cleanup: true
    provider: script
    script: scp -o StrictHostKeyChecking=no -i key ponscr.zip ${UPLOAD_SERVER}/umineko-`cat buildinfo.txt`.zip 2>/dev/null
    on:
      branch: mod
  - skip_cleanup: true
    provider: script
    script: file ponscr.zip && echo ciconia-`cat buildinfo.txt`.zip && bash -c "scp -o StrictHostKeyChecking=no -i key ponscr.zip ${UPLOAD_SERVER}/ciconia-`cat buildinfo.txt`.zip 2>/dev/null"
    on:
      branch: whtest
before_cache:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then $msys2 pacman --sync --clean --noconfirm; fi
cache:
  directories:
    - /C/tools/msys64
