matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      env: STEAMLESS=YES
    - os: linux
      dist: trusty
      language: cpp
    - os: osx
      osx_image: xcode9.4
      language: cpp
before_install:
  - bash .travis_before_install.sh
script:
  - bash .travis_run.sh
deploy:
  - skip_cleanup: true
    provider: script
    script: scp -o StrictHostKeyChecking=no -i key src/ponscr* ${UPLOAD_SERVER}/umineko-`cat buildinfo.txt` 2>/dev/null
    on:
      branch: mod